set(LV_EDITOR_PROJECT_SOURCES)
list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Souvenir_Bold_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/main/main_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui.c)